// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRegistry(arg1) {
  return window['go']['main']['App']['DeleteRegistry'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Greet2(arg1) {
  return window['go']['main']['App']['Greet2'](arg1);
}

export function SearchRegistry(arg1) {
  return window['go']['main']['App']['SearchRegistry'](arg1);
}
